version: "3"
services:
  mysql-db:
    image: mysql:8.0
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: flyway-study
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"